# media.py
import os

def get_media_dict():
    # Sesuaikan path folder "media" tempat lo naro gambar/video
    base_path = os.path.join(os.path.dirname(__file__), "media")

    return {
        # Exercises
        "squats": os.path.join(base_path, "squats.jpg"),
        "yoga": os.path.join(base_path, "yoga.jpg"),
        "deadlifts": os.path.join(base_path, "deadlifts.jpg"),
        "bench_presses": os.path.join(base_path, "bench_press.jpg"),
        "overhead_presses": os.path.join(base_path, "overhead_press.jpg"),
        "brisk_walking": os.path.join(base_path, "brisk_walking.jpg"),
        "cycling": os.path.join(base_path, "cycling.jpg"),
        "running": os.path.join(base_path, "running.jpg"),
        "swimming": os.path.join(base_path, "swimming.jpg"),
        "dancing": os.path.join(base_path, "dancing.jpg"),
        "walking": os.path.join(base_path, "walking.jpg"),

        "squat": os.path.join(base_path, "squats.jpg"),
        "yoga": os.path.join(base_path, "yoga.jpg"),
        "deadlift": os.path.join(base_path, "deadlifts.jpg"),
        "bench_press": os.path.join(base_path, "bench_press.jpg"),
        "overhead_presses": os.path.join(base_path, "overhead_press.jpg"),
        "brisk_walking": os.path.join(base_path, "brisk_walking.jpg"),
        "walking": os.path.join(base_path, "walking.jpg"),
        "outdoor_cycling": os.path.join(base_path, "cycling.jpg"),
        "running": os.path.join(base_path, "running.jpg"),
        "swimming": os.path.join(base_path, "swimming.jpg"),
        "cardio_dance": os.path.join(base_path, "dancing.jpg"),
        #blom
        "push_up": os.path.join(base_path, "push_up.jpg"),
        "plank": os.path.join(base_path, "plank.jpg"),
        "side_plank": os.path.join(base_path, "side_plank.jpg"),
        "wall_plank": os.path.join(base_path, "wall_plank.jpg"),
        "wall_squat": os.path.join(base_path, "wall_squat.jpg"),
        "chair_squat": os.path.join(base_path, "chair_squat.jpg"),
        "goblet_squat": os.path.join(base_path, "goblet_squat.jpg"),
        "lunges": os.path.join(base_path, "lunges.jpg"),
        "hip_bridge": os.path.join(base_path, "hip_bridge.jpg"),
        "hip_hinge": os.path.join(base_path, "hip_hinge.jpg"),
        "kettlebell_swing": os.path.join(base_path, "kettlebell_swing.jpg"),
        "russian_twist": os.path.join(base_path, "russian_twist.jpg"),
        "reverse_crunch": os.path.join(base_path, "reverse_crunch.jpg"),
        "front_plank": os.path.join(base_path, "front_plank.jpg"),
        "farmers_walk": os.path.join(base_path, "farmers_walk.jpg"),
        "elliptical": os.path.join(base_path, "elliptical.jpg"),
        "stair_climber": os.path.join(base_path, "stair_climber.jpg"),
        "treadmill": os.path.join(base_path, "treadmill.jpg"),
        "stationary_bike": os.path.join(base_path, "stationary_bike.jpg"),
        "aqua_jogging": os.path.join(base_path, "aqua_jogging.jpg"),
        "assisted_pull_up": os.path.join(base_path, "assisted_pull_up.jpg"),
        "assisted_lat_pull_down": os.path.join(base_path, "assisted_lat_pull_down.jpg"),
        "lat_pull_down": os.path.join(base_path, "lat_pull_down.jpg"),
        "pull_up": os.path.join(base_path, "pull_up.jpg"),
        "band_row": os.path.join(base_path, "band_row.jpg"),
        "resistance_band_row": os.path.join(base_path, "resistance_band_row.jpg"),
        "seated_cable_row": os.path.join(base_path, "seated_cable_row.jpg"),
        "seated_row": os.path.join(base_path, "seated_row.jpg"),
        "dumbbell_row": os.path.join(base_path, "dumbbell_row.jpg"),
        "barbell_back_squat": os.path.join(base_path, "barbell_back_squat.jpg"),
        "dumbbell_squat": os.path.join(base_path, "dumbbell_squat.jpg"),
        "romanian_deadlift": os.path.join(base_path, "romanian_deadlift.jpg"),
        "leg_press": os.path.join(base_path, "leg_press.jpg"),
        "leg_extension": os.path.join(base_path, "leg_extension.jpg"),
        "leg_curl": os.path.join(base_path, "leg_curl.jpg"),
        "chest_press": os.path.join(base_path, "chest_press.jpg"),


        # Equipment (31)
        "dumbbell": os.path.join(base_path, "dumbbells.jpg"),
        "resistance_band": os.path.join(base_path, "resistance_bands.jpg"),
        "barbell": os.path.join(base_path, "barbells.jpg"),
        "blood_glucose_monitor": os.path.join(base_path, "blood_glucose_monitor.jpg"),
        "light_athletic_shoes": os.path.join(base_path, "light_athletic_shoes.jpg"),
        "ellipticals_machine": os.path.join(base_path, "ellipticals.jpg"),
        "indoor_rowers": os.path.join(base_path, "indoor_rowers.jpg"),
        "treadmill_machine": os.path.join(base_path, "treadmill_machine.jpg"),
        "rowing_machine": os.path.join(base_path, "rowing_machine.jpg"),
        "kettlebell": os.path.join(base_path, "kettlebell.jpg"),
        "yoga_mat": os.path.join(base_path, "yoga_mat.jpg"),
        #blom
        "assisted_pull_up_machine": os.path.join(base_path, "assisted_pull_up_machine.jpg"),
        "bench": os.path.join(base_path, "bench.jpg"),
        "box": os.path.join(base_path, "box.jpg"),
        "cable_row_machine": os.path.join(base_path, "cable_row_machine.jpg"),
        "chest_press_machine": os.path.join(base_path, "chest_press_machine.jpg"),
        "farmer_walk_handles": os.path.join(base_path, "farmer_walk_handles.jpg"),
        "flat_bench": os.path.join(base_path, "flat_bench.jpg"),
        "incline_bench": os.path.join(base_path, "incline_bench.jpg"),
        "incline_press_machine": os.path.join(base_path, "incline_press_machine.jpg"),
        "lat_pull_down_machine": os.path.join(base_path, "lat_pull_down_machine.jpg"),
        "leg_curl_machine": os.path.join(base_path, "leg_curl_machine.jpg"),
        "leg_extension_machine": os.path.join(base_path, "leg_extension_machine.jpg"),
        "leg_press_machine": os.path.join(base_path, "leg_press_machine.jpg"),
        "medicine_ball": os.path.join(base_path, "medicine_ball.jpg"),
        "plank_setup": os.path.join(base_path, "plank_setup.jpg"),
        "pull_up_bar": os.path.join(base_path, "pull_up_bar.jpg"),
        "seated_row_machine": os.path.join(base_path, "seated_row_machine.jpg"),
        "smith_machine": os.path.join(base_path, "smith_machine.jpg"),
        "squat_rack": os.path.join(base_path, "squat_rack.jpg"),
        "strap": os.path.join(base_path, "strap.jpg"),

        # Vegetables
        "garlic": os.path.join(base_path, "garlic.jpg"),
        "carrots": os.path.join(base_path, "carrots.jpg"),
        "lettuce": os.path.join(base_path, "lettuce.jpg"),
        "sweet_potato": os.path.join(base_path, "sweet_potato.jpg"),
        "roma_tomatoes": os.path.join(base_path, "roma_tomatoes.jpg"),
        "green_pepper": os.path.join(base_path, "green_pepper.jpg"), # Typo fix
        "tomatoes": os.path.join(base_path, "tomatoes.jpg"),
        "leafy_greens": os.path.join(base_path, "leafy_greens.jpg"),
        "broccoli": os.path.join(base_path, "broccoli.jpg"),
        "capers": os.path.join(base_path, "capers.jpg"),
        "iceberg_lettuce": os.path.join(base_path, "iceberg_lettuce.jpg"),
        "mixed_greens": os.path.join(base_path, "mixed_greens.jpg"),
        "cherry_tomatoes": os.path.join(base_path, "cherry_tomatoes.jpg"),
        "cucumbers": os.path.join(base_path, "cucumbers.jpg"),
        "celery": os.path.join(base_path, "celery.jpg"),
        "mushroom": os.path.join(base_path, "mushroom.jpg"), # Typo fix
        "water_chestnuts": os.path.join(base_path, "water_chestnuts.jpg"),
        "onion": os.path.join(base_path, "onion.jpg"),
        "spinach": os.path.join(base_path, "spinach.jpg"),

        # Protein
        "red_meats": os.path.join(base_path, "red_meats.jpg"),
        "poultry": os.path.join(base_path, "poultry.jpg"),
        "chicken": os.path.join(base_path, "chicken.jpg"),
        "eggs": os.path.join(base_path, "eggs.jpg"),
        "dairy_products": os.path.join(base_path, "dairy_products.jpg"),
        "fish": os.path.join(base_path, "fish.jpg"),
        "legumes": os.path.join(base_path, "legumes.jpg"),
        "nuts": os.path.join(base_path, "nuts.jpg"),
        "tofu": os.path.join(base_path, "tofu.jpg"),
        "low-fat_dairy_products": os.path.join(base_path, "low-fat_dairy_products.jpg"),
        "cheese_sandwich": os.path.join(base_path, "cheese_sandwich.jpg"),
        "baru_nuts": os.path.join(base_path, "baru_nuts.jpg"),
        "beech_nuts": os.path.join(base_path, "beech_nuts.jpg"),
        "squash_seeds": os.path.join(base_path, "squash_seeds.jpg"),
        "mixed_teff": os.path.join(base_path, "mixed_teff.jpg"),
        "peanut_butter": os.path.join(base_path, "peanut_butter.jpg"),
        "jelly_sandwich": os.path.join(base_path, "jelly_sandwich.jpg"),
        "black_walnut": os.path.join(base_path, "black_walnut.jpg"),
        "hemp_seeds": os.path.join(base_path, "hemp_seeds.jpg"),
        "cheese": os.path.join(base_path, "cheese.jpg"),
        "cottage_cheese": os.path.join(base_path, "cottage_cheese.jpg"), # Typo fix
        "skim_milk": os.path.join(base_path, "skim_milk.jpg"),
        "low_fat_milk": os.path.join(base_path, "low_fat_milk.jpg"), # Typo fix

        # Juice
        "fruit_juice": os.path.join(base_path, "fruit_juice.jpg"),
        "apple_juice": os.path.join(base_path, "apple_juice.jpg"),
        "mango_juice": os.path.join(base_path, "mango_juice.jpg"),
        "carrot_juice": os.path.join(base_path, "carrot_juice.jpg"),
        "watermelon_juice": os.path.join(base_path, "watermelon_juice.jpg"),
        "beetroot_juice": os.path.join(base_path, "beetroot_juice.jpg"),
        "aloe_vera_juice": os.path.join(base_path, "aloe_vera_juice.jpg"),
        "cold-pressed_juice": os.path.join(base_path, "cold-pressed_juice.jpg"),
        "green_juice": os.path.join(base_path, "green_juice.jpg"),
        "kale_juice": os.path.join(base_path, "kale_juice.jpg"), # Placeholder, gak ada di list
        "spinach_juice": os.path.join(base_path, "spinach_juice.jpg"), # Placeholder
        "cucumber_juice": os.path.join(base_path, "cucumber_juice.jpg"), # Placeholder
        "celery_juice": os.path.join(base_path, "celery_juice.jpg"), # Placeholder


        #tumpeng gizi
        "nasi": os.path.join(base_path, "nasi.jpg"),
        "kentang": os.path.join(base_path, "kentang.jpg"),
        "telur": os.path.join(base_path, "telur.jpg"),
        "roti_gandum": os.path.join(base_path, "roti_gandum.jpg"),
        "ikan": os.path.join(base_path, "ikan.jpg"),
        "jagung": os.path.join(base_path, "jagung.jpg"),
        "singkong": os.path.join(base_path, "singkong.jpg"),
        "ubi": os.path.join(base_path, "ubi.jpg"),
        "bayam": os.path.join(base_path, "bayam.jpg"),
        "kangkung": os.path.join(base_path, "kangkung.jpg"),
        "wortel": os.path.join(base_path, "wortel.jpg"),
        "tomat": os.path.join(base_path, "tomat.jpg"),
        "brokoli": os.path.join(base_path, "brokoli.jpg"),
        "jeruk": os.path.join(base_path, "jeruk.jpg"),
        "apel": os.path.join(base_path, "apel.jpg"),
        "pisang": os.path.join(base_path, "pisang.jpg"),
        "pepaya": os.path.join(base_path, "pepaya.jpg"),
        "tahu": os.path.join(base_path, "tahu.jpg"),
        "tempe": os.path.join(base_path, "tempe.jpg"),
        "kacang-kacangan": os.path.join(base_path, "kacang-kacangan.jpg"),
        "ayam_tanpa_kulit": os.path.join(base_path, "ayam_tanpa_kulit.jpg"),
        "daging_tanpa_lemak": os.path.join(base_path, "daging_tanpa_lemak.jpg"),
        "susu_rendah_lemak": os.path.join(base_path, "susu_rendah_lemak.jpg"),
    }